### ISSUE TITLE
Arbeitsbreite neu berechnen

### ISSUE THREAD

**Issue by PBSMods** [ZhooL/FS25_EnhancedVehicle#11]
Mit der Tasten-Config STRG(rechts)+1(Nummernblock) erscheint zwar das Dialogfeld, Arbeitsbreite neu berechnen, aber es ändert sich nichts. Ich habe es getestet, in dem ich die Arbeitsbreite massiv veränderte und dann diese Tasten-Config verwendete.

**Comment by ZhooL** [comment]
Ich sehe keine Probleme mit der Arbeitsbreite und deren Berechnung oder Neuberechnung. Ich vermute eher, du hast das "Arbeitsbreite neu berechnen" falsch verstanden. Ich mach das Issue zu, aber wenn du magst, kannst du es ja nochmal genauer beschrieben, was deiner Meinung nach passieren sollte, wenn man den Knopf drückt.
