### ISSUE TITLE
LUA call stack  "renderOverlay"

### ISSUE THREAD

**Issue by HappyM89** [ZhooL/FS25_EnhancedVehicle#13]
Hallo erst mal Danke Für das Skript.

Leider bekomme ich diesen Error :

Vielleicht hilft dir ja die Log weiter.
Ich freue mich auf das kommete Update.

Mit freundlichen Grüßen

2024-11-30 22:42 
Script error in renderOverlay: renderOverlay is only allowed in 'draw' callbacks.
LUA call stack:
  =[C]:-1 renderOverlay
  =dataS/scripts/gui/base/Overlay.lua:243 render
  =D:/Dokumente/My Games/FarmingSimulator2025/mods/FS25_EnhancedVehicle/ui/FS25_EnhancedVehicle_HUD.lua:644 drawHUD
  =D:/Dokumente/My Games/FarmingSimulator2025/mods/FS25_EnhancedVehicle/FS25_EnhancedVehicle.lua:1233 onDraw
  =dataS/scripts/specialization/SpecializationUtil.lua:44 raiseEvent
  =dataS/scripts/vehicles/Vehicle.lua:2016 draw
  =dataS/scripts/vehicles/specializations/HUDInfoTrigger.lua:89 onUpdate
  =dataS/scripts/specialization/SpecializationUtil.lua:44 raiseEvent
  =dataS/scripts/vehicles/Vehicle.lua:1879 update
  =dataS/scripts/network/NetworkNode.lua:164 updateActiveObjects
  =dataS/scripts/network/Server.lua:64 update
  =dataS/scripts/BaseMission.lua:1017 update
  =dataS/scripts/FSBaseMission.lua:1936 update
  =dataS/scripts/mission00.lua:658 update
  =dataS/scripts/main.lua:1193 update
2024-11-30 22:42 
Script error in renderOverlay: renderOverlay is only allowed in 'draw' callbacks.
LUA call stack:
  =[C]:-1 renderOverlay

[log.txt](https://github.com/user-attachments/files/17967141/log.txt)

**Comment by ZhooL** [comment]
Kannst du etwas genauer beschrieben, was du gemacht hast, als der Fehler aufgetreten ist. Warst du in einem Fahrzeug? Wenn ja, was für eins. War das HUD an/aus? Sowas halt...

**Comment by ZhooL** [comment]
Das wäre sehr hilfreich. Aktuell hab ich keine Idee, wie/wann der Fehler zu Stande gekommen ist

**Comment by HappyM89** [comment]
Servus, also konnte den Fehler jetzt eingrenzen.
er müsste was mit dem John Deer 3650 und Kuhn RA142 zu tun haben.
wenn ich den mit dem Giantshelfer zum Ziel schicke und er losfährt kommen die LUA´s.
Also auf der karte Ziel wählen und starten.

hier noch mal die Log

[log.txt](https://github.com/user-attachments/files/17968761/log.txt)

**Comment by ZhooL** [comment]
Sollte jetzt nicht mehr auftreten.
