### ISSUE TITLE
Kamera

### ISSUE THREAD

**Issue by timmi4026** [ZhooL/FS25_EnhancedVehicle#14]
Moin, hab mal eine Frage wäre es möglich  die Kamera in der Innenansicht so zu steuern das man beim rückwärtsfahren nach hinten guckt? Vllt optional abschaltbar wer es nicht nutzen will?

LG. Timmi

**Comment by ZhooL** [comment]
Hi, sorry, so ein Feature ist nicht geplant. Ggf. kommt so etwas wieder vom Autor von VCA.
