### ISSUE TITLE
Config menu opens but no text

### ISSUE THREAD

**Issue by K-R-U-E** [ZhooL/FS25_EnhancedVehicle#17]
When hit Right Ctrl plus /  the config menu opens, however it's blank just boxes where things should go.  console shows a gettext lua error on line 56 of the ui config.  This didn't happen with 1.1 however it happesn now with 1.1 and 1.1.1.0

**Comment by K-R-U-E** [comment]
![bug](https://github.com/user-attachments/assets/f8549ec4-7e8f-4491-bcb4-e15f34b3e5c4)

**Comment by ZhooL** [comment]
Please use the right download link from https://majo76.de or Github repo releases page. Your mod name is wrong.

**Comment by K-R-U-E** [comment]
i've downloaded it straight from your github page.  just downloaded 1.1.2.0 that you just released and same issue

**Comment by K-R-U-E** [comment]
oh wait,  is it because i manually changed the name of the .zip?  i added _GitHub on it to remind me tha tone was from github for updates
