### ISSUE TITLE
LUA call stack 2414

### ISSUE THREAD

**Issue by HappyM89** [ZhooL/FS25_EnhancedVehicle#21]
Hi, 
Error tauchte auf bei neu setzen der Fahrspur. 
Fahrzeuge: 6R, Krone Pickpack

[log.txt](https://github.com/user-attachments/files/17970161/log.txt)

**Comment by ZhooL** [comment]
Okay, ich kann es nachstellen... scheinbar nur wenn das Fahrzeug genau in 0° schaut und man dann die Fahrtrichtung erneut reinsnapped. Ich schau mal nach einem Workaround

**Comment by ZhooL** [comment]
Should be fixed in 1.1.2.2

**Comment by HappyM89** [comment]
Top danke für die schnelle Reaktion.
