### ISSUE TITLE
Pferde im Multiplayer

### ISSUE THREAD

**Issue by JimmyBeam1990** [ZhooL/FS25_EnhancedVehicle#24]
Wenn man auf nem Pferd sitzt und reiten will wird der Bildschirm wird schwarz oder das UI verschwidnet und in der log kommt:

C:/Users/danye/OneDrive/Dokumente/My Games/FarmingSimulator2025/mods/FS25_EnhancedVehicle/ui/FS25_EnhancedVehicle_HUD.lua:671: attempt to index nil with 'is'
2024-12-02 13:09 Error: Running LUA method 'draw'.

das ganze ist auf einem Dedizierten Server. dort ist kein fehler in der log

**Comment by ZhooL** [comment]
Sollte in der neusten Version gefixt sein. https://github.com/ZhooL/FS25_EnhancedVehicle/releases/latest/download/FS25_EnhancedVehicle.zip
