### ISSUE TITLE
Translation to Czech

### ISSUE THREAD

**Issue by VidhosticeSDK** [ZhooL/FS25_EnhancedVehicle#26]
Hi,
can you please include Czech localization in your mod.

[translation_cz.txt](https://github.com/user-attachments/files/17983070/translation_cz.txt)

**Comment by ZhooL** [comment]
Hi, unfortunately, your file is incomplete. It must contain of 136 lines in total.

**Comment by VidhosticeSDK** [comment]
Hello,
I am sending the corrected version (sorry for my mistake).

[translation_cz.txt](https://github.com/user-attachments/files/18004747/translation_cz.txt)

**Comment by ZhooL** [comment]
No worries :-) Will be included in the next release.
