### ISSUE TITLE
Frage zur Arbeitsbreiten Berechnung.

### ISSUE THREAD

**Issue by HappyM89** [ZhooL/FS25_EnhancedVehicle#29]
Hallo, 
Welchen eintrag muss ich in der Mod.Xml anpassen das die breiten berechnung passt?

Also ich habe einen Mod erstellt und dort die Arbeitsbreite verändert im Editor von 1.5 auf 4.5 und in der Xml den eintarg <workingWidth> angepasst. Wenn ich jetzt die Arbeitsbreite berechnen lasse haut er mir als noch die Orginale breite von 1.5m rein.

vielleicht kannst du mir ja bitte weiter helfen.

**Comment by ZhooL** [comment]
Sorry, ich kann dir bei Fahrzeugen, Geräten, Gebäuden und Maps nicht helfen. Da hab ich keine Ahnung von.

**Comment by HappyM89** [comment]
okay, dachte nur das die Breitenberechnug von deinem Skript kommt. Dann schau ich mal weiter.
