### ISSUE TITLE
Suggestion: fuel range calculator

### ISSUE THREAD

**Issue by KingdomHallChef** [ZhooL/FS25_EnhancedVehicle#31]
It would fit this mod to have a fuel range calculator on the UI, selectable in either distance left (kilometers, or miles for those who use that) or hours left, based on current fuel amount (any fuel type) and consumption for each vehicle.

**Comment by ZhooL** [comment]
Thanks for the idea, but I have no plans to implement such thing. It won't work anyway easily in multiplayer due to engine limitations.
