### ISSUE TITLE
error LUA

### ISSUE THREAD

**Issue by criss20ster** [ZhooL/FS25_EnhancedVehicle#32]
Error: Running LUA method 'update'.
H:/ModyFS25/FS25_EnhancedVehicle1_1_3_1/ui/FS25_EnhancedVehicle_UI.lua:56: attempt to index nil with 'getText'

**Comment by ZhooL** [comment]
Always use this link to download the latest version and never rename the .zip file. https://github.com/ZhooL/FS25_EnhancedVehicle/releases/latest/download/FS25_EnhancedVehicle.zip
