### ISSUE TITLE
Spur verschieben / Arbeitsbreite ändern nicht möglich

### ISSUE THREAD

**Issue by scud1984** [ZhooL/FS25_EnhancedVehicle#34]
Kann weder die Spur nach links oder rechts (STRG rechts + +/-) noch die arbeitsbreite ändern (SHIFT rechts + +/-)
auch das neu zuweisen auf andere Tasten brachte keinen Erfolg

**Comment by ZhooL** [comment]
Sorry, kann ich dir nicht helfen. Schau, dass du keine Konflikte mir anderen Mods hast. Und Numpad +/- ... nicht das normale +/-
