### ISSUE TITLE
Erweiterung des Vanilla GPS

### ISSUE THREAD

**Issue by H4nnib4l22** [ZhooL/FS25_EnhancedVehicle#4]
Hallo :) Erstmal danke für deine Arbeit und dem zügigen zur Verfügung stellen von EV für den 25er :)

Nun zu meiner kleinen Frage :) Ist es geplant funktionen deines GPS auf das Vanilla zu übertragen? Ich rede da speziell von der Funktion was am ende der Bahn passieren soll :) 

VG und Cheers

**Comment by ZhooL** [comment]
Hi, danke für dein Feedback.

Es ist nicht geplant, in das eingebaute Helfer/Spurführungssystem einzugreifen.

**Comment by ZhooL** [comment]
Danke, aber dieses Mod wird nicht auf Modhub erscheinen.
