### ISSUE TITLE
Menu in Mp nicht benutzbar

### ISSUE THREAD

**Issue by DEKoelle** [ZhooL/FS25_EnhancedVehicle#5]
hy ich habe das Menu so in MP
![Unbenannt](https://github.com/user-attachments/assets/33dc3ede-ec7e-480b-b00e-bbc74edffb98)

**Comment by ZhooL** [comment]
Bitte die log.txt hier posten/anhängen

**Comment by ZhooL** [comment]
Kannst du das ganze Log posten? Da scheint mir noch ein anderer Fehler zu sein weiter oben im Log

**Comment by DEKoelle** [comment]
[log.txt](https://github.com/user-attachments/files/17962871/log.txt)

**Comment by ZhooL** [comment]
Danke. Auf den ersten Blick nichts zu sehen... ich muß versuchen, dass nachzustellen. Was für eine Art Multiplayer? Mit einem Dedicated Server oder bist du der Host von einem Multiplayerspiel?

**Comment by DEKoelle** [comment]
Dedicated Server Zurzeit noch bei Nitrado

**Comment by ZhooL** [comment]
Available mod: (Hash: 22eb54a056d5678bf146d21761ca5ee4) (Version: 1.1.0.0) FS25_EnhancedVehicl
Was auch immer du gemacht hast - das ist nicht die Original FS25_EnhancedVehicle.zip von dieser Seite. Der korrekte Hash und Name des Mods wäre:
Available mod: (Hash: 9407d2537e11126f061e2ce6328726fb) (Version: 1.1.0.0) FS25_EnhancedVehicle

Bitte neu runterladen und nicht drin rumfummeln ;-)

**Comment by DEKoelle** [comment]
also ich habe die runter geladen und die main datei die man bekommt entpackt und die einzelne Datein in eine Zip neu ein gepackt mehr nicht

**Comment by ZhooL** [comment]
Bitte den richtige angebotenen Download-Link verwenden: https://github.com/ZhooL/FS25_EnhancedVehicle/releases/latest/download/FS25_EnhancedVehicle.zip

**Comment by DEKoelle** [comment]
ja habe den fehler gefunden sorry dafür aber ich habe FS25_EnhancedVehicl dahinter das e versehentlcih gelöscht daher hat das nmicht funktioniert jetzt geht es sorry dafür
