### ISSUE TITLE
Auf / Zuklappen vorne und hinten

### ISSUE THREAD

**Issue by Unix0815** [ZhooL/FS25_EnhancedVehicle#7]
Hallo, schöner Mod, allerdings fehlt mir eine wichtige Funktion. Man kann zwar wunderbar die Front und Heckhydraulik getrennt hoch und runterfahren oder an und ausschalten, aber es fehlt das getrennte auf und zuklappen für vorne und hinten. Wäre es möglich das auch noch umzusetzen? Dann müsste man nicht ständig mit G durch die Geräte switchen zum auf / zuklappen.

**Comment by ZhooL** [comment]
Ist in der 1.1.2.0 drin. Per default auf Alt+5/6 für alles hinten/vorne klappen. Aber wie immer: nur Anbaugeräte. Fest an einem Fahrzeug verbaute zB Schneidwerke werden nicht beachtet.
